use_frameworks!
platform :ios, '9.0'

target 'NVActivityIndicatorViewExample' do
  pod 'NVActivityIndicatorView', :git => 'https://github.com/LeeShiYoung/NVActivityIndicatorView.git'

  target 'NVActivityIndicatorViewTests'
end
